import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  await prisma.testimonial.deleteMany()
  await prisma.inquiry.deleteMany()
  await prisma.application.deleteMany()
  await prisma.favorite.deleteMany()
  await prisma.agentReview.deleteMany()
  await prisma.property.deleteMany()
  await prisma.agent.deleteMany()

  // ── Agents ─────────────────────────────────────────────────────────────────

  const michael = await prisma.agent.create({
    data: {
      name: 'Michael Reeves',
      slug: 'michael-reeves',
      title: 'Licensed Real Estate Broker',
      bio: 'A Halifax native with over 14 years in Atlantic Canada real estate. Michael specialises in waterfront properties, downtown condos, and investment portfolios across the Halifax Regional Municipality.',
      photo: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80',
      email: 'michael@altaverealty.com',
      phone: '+1 (902) 555-0100',
      specialties: ['Luxury Rentals', 'Waterfront Sales', 'Investment'],
      languages: ['English', 'French'],
      yearsExperience: 14,
      propertiesSold: 312,
      rating: 4.9,
      isFeatured: true,
    },
  })

  const sarah = await prisma.agent.create({
    data: {
      name: 'Sarah Thornton',
      slug: 'sarah-thornton',
      title: 'Senior Real Estate Agent',
      bio: 'Sarah brings a data-driven approach to Halifax real estate, helping clients navigate the competitive HRM market with confidence. Specialising in residential rentals and first-time buyers.',
      photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80',
      email: 'sarah@altaverealty.com',
      phone: '+1 (902) 555-0101',
      specialties: ['Rentals', 'First-Time Buyers', 'Condos'],
      languages: ['English'],
      yearsExperience: 8,
      propertiesSold: 198,
      rating: 4.8,
      isFeatured: true,
    },
  })

  const david = await prisma.agent.create({
    data: {
      name: 'David Nguyen',
      slug: 'david-nguyen',
      title: 'Commercial & Residential Specialist',
      bio: 'David focuses on commercial leasing and high-end residential sales across Bedford, Clayton Park, and Dartmouth. Known for his sharp market analysis and client-first approach.',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
      email: 'david@altaverealty.com',
      phone: '+1 (902) 555-0102',
      specialties: ['Commercial', 'Residential Sales', 'New Developments'],
      languages: ['English', 'Vietnamese', 'French'],
      yearsExperience: 10,
      propertiesSold: 241,
      rating: 4.9,
      isFeatured: true,
    },
  })

  const emma = await prisma.agent.create({
    data: {
      name: 'Emma Clarke',
      slug: 'emma-clarke',
      title: 'Rental & Relocation Specialist',
      bio: 'Emma is the go-to expert for relocations to Halifax, working with professionals and families moving to Nova Scotia. She makes the transition seamless, finding the perfect home fast.',
      photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80',
      email: 'emma@altaverealty.com',
      phone: '+1 (902) 555-0103',
      specialties: ['Relocation', 'Rentals', 'Townhouses'],
      languages: ['English'],
      yearsExperience: 6,
      propertiesSold: 154,
      rating: 4.7,
      isFeatured: true,
    },
  })

  // ── Properties ─────────────────────────────────────────────────────────────

  await prisma.property.createMany({
    data: [
      // Downtown Halifax
      {
        slug: 'downtown-waterfront-2br-condo',
        title: 'Waterfront 2BR Condo — Downtown Halifax',
        description:
          'Stunning two-bedroom condo perched on Halifax Harbour with panoramic water views. Features floor-to-ceiling windows, quartz countertops, in-unit laundry, and a private balcony. Steps from the boardwalk, restaurants, and transit.',
        type: 'CONDO',
        status: 'RENT',
        price: 2800,
        address: '1583 Barrington St, Unit 1204',
        city: 'Halifax',
        area: 'Downtown Halifax',
        state: 'NS',
        zipCode: 'B3J 1Z5',
        lat: 44.6488,
        lng: -63.5752,
        bedrooms: 2,
        bathrooms: 2,
        sqft: 1050,
        yearBuilt: 2019,
        parking: 1,
        amenities: ['Harbour Views', 'In-unit Laundry', 'Gym', 'Concierge', 'Rooftop Terrace', 'Dishwasher'],
        images: [
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&q=80',
          'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80',
          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80',
          'https://images.unsplash.com/photo-1555912098-dc38d3cd48d0?w=900&q=80',
        ],
        isFeatured: true,
        isNew: true,
        isHot: true,
        petFriendly: false,
        agentId: michael.id,
      },
      {
        slug: 'downtown-luxury-1br-suite',
        title: 'Luxury 1BR Suite — Spring Garden Area',
        description:
          'Modern one-bedroom suite in the heart of the Spring Garden corridor. Open-concept layout, 9-foot ceilings, exposed concrete accents, and premium finishes throughout. Building amenities include a fitness studio and rooftop patio.',
        type: 'CONDO',
        status: 'RENT',
        price: 2100,
        address: '5668 Spring Garden Rd, Unit 802',
        city: 'Halifax',
        area: 'Downtown Halifax',
        state: 'NS',
        zipCode: 'B3J 1H2',
        lat: 44.6432,
        lng: -63.5835,
        bedrooms: 1,
        bathrooms: 1,
        sqft: 720,
        yearBuilt: 2021,
        parking: 1,
        amenities: ['Gym', 'Rooftop Patio', 'In-unit Laundry', 'Dishwasher', 'Storage Locker'],
        images: [
          'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&q=80',
          'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=900&q=80',
          'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&q=80',
          'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80',
        ],
        isFeatured: true,
        isNew: true,
        petFriendly: true,
        agentId: sarah.id,
      },
      {
        slug: 'downtown-halifax-loft-for-sale',
        title: 'Contemporary Loft — Downtown Halifax',
        description:
          "Rare downtown loft conversion in a heritage building. 14-foot ceilings, exposed brick, polished concrete floors, and massive industrial windows. Two bedrooms, gourmet kitchen, private rooftop access.",
        type: 'LOFT',
        status: 'SALE',
        price: 579000,
        address: '1561 Hollis St, Unit 310',
        city: 'Halifax',
        area: 'Downtown Halifax',
        state: 'NS',
        zipCode: 'B3J 1V8',
        lat: 44.6470,
        lng: -63.5760,
        bedrooms: 2,
        bathrooms: 2,
        sqft: 1380,
        yearBuilt: 2017,
        parking: 1,
        amenities: ['Heritage Building', 'Rooftop Access', 'In-unit Laundry', 'Dishwasher', 'Bike Storage'],
        images: [
          'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=900&q=80',
          'https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=900&q=80',
          'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80',
          'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&q=80',
        ],
        isFeatured: true,
        isHot: true,
        petFriendly: true,
        agentId: michael.id,
      },
      // North End Halifax
      {
        slug: 'north-end-2br-character-home',
        title: 'Charming 2BR Character Home — North End',
        description:
          'Beautifully renovated semi-detached character home in the vibrant North End. Hardwood throughout, updated kitchen with stainless appliances, private backyard with deck, and a full unfinished basement for storage.',
        type: 'RESIDENTIAL',
        status: 'RENT',
        price: 2450,
        address: '2156 Gottingen St',
        city: 'Halifax',
        area: 'North End',
        state: 'NS',
        zipCode: 'B3K 3C1',
        lat: 44.6638,
        lng: -63.5900,
        bedrooms: 2,
        bathrooms: 1,
        sqft: 1100,
        yearBuilt: 1940,
        amenities: ['Backyard Deck', 'Hardwood Floors', 'Dishwasher', 'Pet Friendly', 'Storage'],
        images: [
          'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=900&q=80',
          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80',
          'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&q=80',
          'https://images.unsplash.com/photo-1555912098-dc38d3cd48d0?w=900&q=80',
        ],
        isFeatured: true,
        petFriendly: true,
        agentId: sarah.id,
      },
      {
        slug: 'north-end-studio-trendy',
        title: 'Trendy Studio — North End Halifax',
        description:
          'Bright and stylish studio in the heart of the North End arts district. Steps from top-rated restaurants, galleries, and the Halifax Farmers Market. Modern finishes, exposed brick, and a Juliet balcony.',
        type: 'STUDIO',
        status: 'RENT',
        price: 1550,
        address: '2305 Agricola St, Unit 201',
        city: 'Halifax',
        area: 'North End',
        state: 'NS',
        zipCode: 'B3K 4C5',
        lat: 44.6610,
        lng: -63.5870,
        bedrooms: 0,
        bathrooms: 1,
        sqft: 490,
        yearBuilt: 2018,
        amenities: ['Exposed Brick', 'Juliet Balcony', 'Dishwasher', 'Pet Friendly', 'Bike Storage'],
        images: [
          'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80',
          'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=900&q=80',
          'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80',
        ],
        isNew: true,
        petFriendly: true,
        agentId: emma.id,
      },
      // South End Halifax
      {
        slug: 'south-end-3br-heritage-home-sale',
        title: 'Heritage 3BR Home — South End Halifax',
        description:
          "Stately three-bedroom Victorian home on one of Halifax's most prestigious streets. Original millwork, updated kitchen, three full baths, and a private garden. Walking distance to Dalhousie University and Point Pleasant Park.",
        type: 'RESIDENTIAL',
        status: 'SALE',
        price: 849000,
        address: '1420 South Park St',
        city: 'Halifax',
        area: 'South End',
        state: 'NS',
        zipCode: 'B3J 2K8',
        lat: 44.6350,
        lng: -63.5750,
        bedrooms: 3,
        bathrooms: 3,
        sqft: 2200,
        yearBuilt: 1912,
        amenities: ['Private Garden', 'Heritage Character', 'Hardwood Floors', 'Updated Kitchen', 'Parking'],
        images: [
          'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80',
          'https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=900&q=80',
          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80',
          'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80',
          'https://images.unsplash.com/photo-1555912098-dc38d3cd48d0?w=900&q=80',
        ],
        isFeatured: true,
        agentId: michael.id,
      },
      {
        slug: 'south-end-2br-condo-sale',
        title: 'Modern 2BR Condo — South End Halifax',
        description:
          'Sophisticated condo in a boutique 12-unit building on the South End waterfront corridor. Two bedrooms, two baths, open living space, stone counters, and a private terrace with city views.',
        type: 'CONDO',
        status: 'SALE',
        price: 619000,
        address: '5657 Inglis St, Unit 5',
        city: 'Halifax',
        area: 'South End',
        state: 'NS',
        zipCode: 'B3H 1K4',
        lat: 44.6380,
        lng: -63.5810,
        bedrooms: 2,
        bathrooms: 2,
        sqft: 1160,
        yearBuilt: 2020,
        parking: 1,
        amenities: ['Private Terrace', 'In-unit Laundry', 'Dishwasher', 'Storage', 'Bike Room'],
        images: [
          'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&q=80',
          'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=900&q=80',
          'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=900&q=80',
          'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&q=80',
        ],
        isNew: true,
        agentId: david.id,
      },
      // Clayton Park
      {
        slug: 'clayton-park-3br-townhouse',
        title: 'Spacious 3BR Townhouse — Clayton Park',
        description:
          'Well-maintained end-unit townhouse in sought-after Clayton Park West. Three bedrooms, two and a half baths, attached single garage, finished rec room, and a fully fenced backyard. Close to Bayers Lake, schools, and transit.',
        type: 'TOWNHOUSE',
        status: 'RENT',
        price: 2700,
        address: '34 Celerity Dr',
        city: 'Halifax',
        area: 'Clayton Park',
        state: 'NS',
        zipCode: 'B3M 4K4',
        lat: 44.6900,
        lng: -63.6700,
        bedrooms: 3,
        bathrooms: 2.5,
        sqft: 1650,
        yearBuilt: 2005,
        parking: 1,
        amenities: ['Attached Garage', 'Fenced Backyard', 'Rec Room', 'In-unit Laundry', 'Dishwasher'],
        images: [
          'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=900&q=80',
          'https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=900&q=80',
          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80',
          'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80',
        ],
        isFeatured: true,
        petFriendly: true,
        agentId: emma.id,
      },
      {
        slug: 'clayton-park-1br-apartment',
        title: 'Bright 1BR Apartment — Clayton Park',
        description:
          'Clean and bright one-bedroom unit in a quiet low-rise building. Updated kitchen and bath, ample closets, and surface parking included. Conveniently located near Bayers Lake shopping, restaurants, and the 80/82 express routes.',
        type: 'RESIDENTIAL',
        status: 'RENT',
        price: 1700,
        address: '110 Lacewood Dr, Unit 204',
        city: 'Halifax',
        area: 'Clayton Park',
        state: 'NS',
        zipCode: 'B3M 3W8',
        lat: 44.6880,
        lng: -63.6640,
        bedrooms: 1,
        bathrooms: 1,
        sqft: 680,
        yearBuilt: 1995,
        parking: 1,
        amenities: ['Surface Parking', 'Updated Kitchen', 'Balcony', 'Storage', 'Pet Friendly'],
        images: [
          'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=900&q=80',
          'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=900&q=80',
          'https://images.unsplash.com/photo-1555912098-dc38d3cd48d0?w=900&q=80',
        ],
        petFriendly: true,
        agentId: sarah.id,
      },
      // Bedford
      {
        slug: 'bedford-waterfront-4br-home-sale',
        title: 'Waterfront 4BR Home — Bedford',
        description:
          "Exceptional executive home on the Bedford Basin with private dock access. Four bedrooms, three full baths, vaulted great room, chef's kitchen with island, three-car garage, and landscaped gardens.",
        type: 'RESIDENTIAL',
        status: 'SALE',
        price: 1250000,
        address: '88 Shore Dr',
        city: 'Bedford',
        area: 'Bedford',
        state: 'NS',
        zipCode: 'B4A 2E5',
        lat: 44.7320,
        lng: -63.6530,
        bedrooms: 4,
        bathrooms: 3,
        sqft: 3400,
        yearBuilt: 2016,
        parking: 3,
        amenities: ['Waterfront', 'Private Dock', "Chef's Kitchen", 'Triple Garage', 'Landscaped Gardens', 'Vaulted Ceilings'],
        images: [
          'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=900&q=80',
          'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&q=80',
          'https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=900&q=80',
          'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80',
          'https://images.unsplash.com/photo-1555912098-dc38d3cd48d0?w=900&q=80',
        ],
        isFeatured: true,
        isHot: true,
        agentId: michael.id,
      },
      {
        slug: 'bedford-2br-townhouse-rent',
        title: 'Modern 2BR Townhouse — Bedford',
        description:
          'Newer townhouse in a desirable Bedford cul-de-sac development. Open main floor, two large bedrooms, 1.5 baths, private patio, and an attached garage. Minutes to the highway, retail, and Lake Banook recreation area.',
        type: 'TOWNHOUSE',
        status: 'RENT',
        price: 2400,
        address: '12 Millrun Court',
        city: 'Bedford',
        area: 'Bedford',
        state: 'NS',
        zipCode: 'B4A 4M7',
        lat: 44.7280,
        lng: -63.6580,
        bedrooms: 2,
        bathrooms: 1.5,
        sqft: 1200,
        yearBuilt: 2022,
        parking: 1,
        amenities: ['Attached Garage', 'Private Patio', 'In-unit Laundry', 'Dishwasher', 'New Build'],
        images: [
          'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=900&q=80',
          'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=900&q=80',
          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80',
        ],
        isNew: true,
        agentId: emma.id,
      },
      // Dartmouth
      {
        slug: 'dartmouth-1br-condo-rent',
        title: 'Modern 1BR Condo — Downtown Dartmouth',
        description:
          'Sleek one-bedroom condo steps from Dartmouth Crossing and the Alderney Ferry terminal. Quartz counters, stainless appliances, in-unit laundry, and a private balcony with harbour glimpses.',
        type: 'CONDO',
        status: 'RENT',
        price: 1900,
        address: '1 Alderney Dr, Unit 615',
        city: 'Dartmouth',
        area: 'Dartmouth',
        state: 'NS',
        zipCode: 'B2Y 4T9',
        lat: 44.6713,
        lng: -63.5539,
        bedrooms: 1,
        bathrooms: 1,
        sqft: 760,
        yearBuilt: 2020,
        parking: 1,
        amenities: ['Ferry Access', 'Harbour Views', 'In-unit Laundry', 'Gym', 'Dishwasher'],
        images: [
          'https://images.unsplash.com/photo-1575517111839-3a3843ee7f5d?w=900&q=80',
          'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&q=80',
          'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=900&q=80',
          'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80',
        ],
        isNew: true,
        agentId: david.id,
      },
      // Fairview
      {
        slug: 'fairview-studio-affordable',
        title: 'Updated Studio — Fairview',
        description:
          'Affordable and stylish studio in a well-managed Fairview building. Freshly painted, new flooring, updated bath, and all utilities included. Transit-friendly location with quick access to the Bayers Road corridor.',
        type: 'STUDIO',
        status: 'RENT',
        price: 1350,
        address: '163 Fairview Ave, Unit 306',
        city: 'Halifax',
        area: 'Fairview',
        state: 'NS',
        zipCode: 'B3N 1K3',
        lat: 44.6680,
        lng: -63.6580,
        bedrooms: 0,
        bathrooms: 1,
        sqft: 440,
        yearBuilt: 1988,
        amenities: ['Utilities Included', 'Updated Bath', 'New Flooring', 'Laundry On-site', 'Storage'],
        images: [
          'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&q=80',
          'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80',
          'https://images.unsplash.com/photo-1555912098-dc38d3cd48d0?w=900&q=80',
        ],
        agentId: sarah.id,
      },
      // Commercial
      {
        slug: 'downtown-commercial-office-suite',
        title: 'Premium Office Suite — Downtown Halifax',
        description:
          'Class A office suite on the 10th floor of a landmark downtown building. 3,200 sqft of open-plan space, boardroom, kitchenette, harbour views, underground parking for 4 vehicles, and on-site property management.',
        type: 'COMMERCIAL',
        status: 'RENT',
        price: 8500,
        address: '1871 Hollis St, Suite 1000',
        city: 'Halifax',
        area: 'Downtown Halifax',
        state: 'NS',
        zipCode: 'B3J 0C3',
        lat: 44.6495,
        lng: -63.5742,
        bathrooms: 2,
        sqft: 3200,
        yearBuilt: 2008,
        parking: 4,
        amenities: ['Harbour Views', 'Boardroom', 'Underground Parking', 'On-site Management', 'High-speed Internet', '24/7 Security'],
        images: [
          'https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&q=80',
          'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=900&q=80',
          'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=900&q=80',
        ],
        isFeatured: true,
        agentId: david.id,
      },
    ],
  })

  // ── Testimonials ────────────────────────────────────────────────────────────

  await prisma.testimonial.createMany({
    data: [
      {
        name: 'Jessica Palmer',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
        role: 'Rented a condo, Downtown Halifax',
        rating: 5,
        content:
          'Altave made our move to Halifax so easy. Sarah found us an incredible waterfront condo within two weeks of us reaching out. The whole process was smooth and professional from start to finish.',
        isVerified: true,
        isFeatured: true,
      },
      {
        name: 'Thomas Bergmann',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
        role: 'Purchased a home, Bedford',
        rating: 5,
        content:
          "Michael negotiated an excellent price on our Bedford waterfront home. His knowledge of the Halifax market is unmatched. We'll never use another agent.",
        isVerified: true,
        isFeatured: true,
      },
      {
        name: 'Priya Sharma',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80',
        role: 'Rented a townhouse, Clayton Park',
        rating: 5,
        content:
          'Emma was fantastic — extremely responsive and went above and beyond to show us properties that matched our criteria. We love our new home in Clayton Park!',
        isVerified: true,
        isFeatured: true,
      },
      {
        name: "Liam O'Connor",
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
        role: 'Leased an office, Downtown Halifax',
        rating: 5,
        content:
          'David sourced a perfect office suite for our tech startup. He understood our needs, negotiated great terms, and the whole process was effortless. Highly recommend Altave for commercial.',
        isVerified: true,
        isFeatured: true,
      },
    ],
  })

  console.log('✅ Halifax seed data created successfully.')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
